### ISSUE TITLE
I can't select cell

### ISSUE THREAD

**Issue by iThanh** [HasanEdain/NPCColorPicker#3]
I can't select cell in collectionView.
When I using Simulator, I must hold "option" in keyboard and select in collection.
Help me, thanks!

**Comment by HasanEdain** [comment]
You are my first support ticket. I'm not near my computer, but I will look when I get home.

**Comment by HasanEdain** [comment]
Can you provide some specifics?
What version of xCode? What target? Which simulator (iPhone model and iOS version)?
Any other details of the problem.

**Comment by HasanEdain** [comment]
I am running in xCode 7.3, iPhone 6s Plus / iOS 9.0 and am not able to replicate.

**Comment by iThanh** [comment]
I am runnning Xcode 7.3.1, iPhone 6S - iOS 9.
I think that is a problem with touch in collectionViewCell.
On the simulator, I must hold down the option key and select or I press long press.

**Comment by HasanEdain** [comment]
running the example app, or in your code?

**Comment by iThanh** [comment]
In my code, Sir.
Sometime, collectionViewDelegate named: didSelectItemAtIndexPath call.
Sometime it not.
Please check it, also. Thanks Sir.

**Comment by HasanEdain** [comment]
Can you run the example app and see if it shows the problem please?

**Comment by iThanh** [comment]
It not error in example app, Sir.

**Comment by HasanEdain** [comment]
So we are looking for a difference between the example app and your code.
Can you show me the code you are using for your ViewController?

**Comment by iThanh** [comment]
self.colorPicker.embedColorPickerInView(self.embedView, forDelegate: self)
self.colorPicker.changeMaskStyle(NPCColorPickerMask.circle)
self.colorPicker.changeDiameter(48)
self.colorPicker.changeColorToGradientArray(["ffffff", "000000", "ff0000", "00ff00", "0000ff"], steps: 10)
self.colorPicker.changeSpaceBetweenColors(4, columns: 4)

Exactly the same in the example code and my code.
I got this error with all CollectionViewCell in my code.
Please!

**Comment by iThanh** [comment]
OK, thank you so much sir. I got it.
Am using Tap Gesture, and no errors when I write:

`tap.cancelsTouchesInView = false`

Thank you Sir, this error just for me.

**Comment by HasanEdain** [comment]
Excellent, glad you found it.
