### ISSUE TITLE
Integration with Cocoapods

### ISSUE THREAD

**Issue by Ponf** [HasanEdain/NPCColorPicker#5]
Hi! Could you please add your control to cocoapods? It will be much easier to use it :)

**Comment by HasanEdain** [comment]
I really don’t like Cocoapods, I think it is a bad tool.
I am happy to make / maintain a Carthage version, but I will not be party to Cocoapods.

**Comment by Ponf** [comment]
I'm sad to hear that, but I understand your point.

Thank you anyway for nice control!

**Comment by HasanEdain** [comment]
Sorry for being grouchy. My day job I spent a year getting rid of Cocoapods… it hurt me a LOT at work.
